/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef PHP_PHP2MCS_H
#define PHP_PHP2MCS_H

extern zend_module_entry php2mcs_module_entry;
#define phpext_php2mcs_ptr &php2mcs_module_entry

#ifdef PHP_WIN32
# define PHP_PHP2MCS_API __declspec(dllexport)
#else
# define PHP_PHP2MCS_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(php2mcs);
PHP_MSHUTDOWN_FUNCTION(php2mcs);
PHP_RINIT_FUNCTION(php2mcs);
PHP_RSHUTDOWN_FUNCTION(php2mcs);
PHP_MINFO_FUNCTION(php2mcs);

ZEND_NAMED_FUNCTION(_wrap_ifd_status_error_set);
ZEND_NAMED_FUNCTION(_wrap_ifd_status_error_get);
ZEND_NAMED_FUNCTION(_wrap_ifd_status_errormsg_set);
ZEND_NAMED_FUNCTION(_wrap_ifd_status_errormsg_get);
ZEND_NAMED_FUNCTION(_wrap_ifd_status_data_set);
ZEND_NAMED_FUNCTION(_wrap_ifd_status_data_get);
ZEND_NAMED_FUNCTION(_wrap_new_ifd_status);
ZEND_NAMED_FUNCTION(_wrap_ifd_last_error);
ZEND_NAMED_FUNCTION(_wrap_ifd_got_error);
ZEND_NAMED_FUNCTION(_wrap_ifd_reset_error);
ZEND_NAMED_FUNCTION(_wrap_ifd_null);
ZEND_NAMED_FUNCTION(_wrap_new_Data);
ZEND_NAMED_FUNCTION(_wrap_copy_Data);
ZEND_NAMED_FUNCTION(_wrap_del_Data);
ZEND_NAMED_FUNCTION(_wrap_Data_name);
ZEND_NAMED_FUNCTION(_wrap_Data_type);
ZEND_NAMED_FUNCTION(_wrap_Data_maxLength);
ZEND_NAMED_FUNCTION(_wrap_Data_length);
ZEND_NAMED_FUNCTION(_wrap_Data_isUnsigned);
ZEND_NAMED_FUNCTION(_wrap_Data_isNull);
ZEND_NAMED_FUNCTION(_wrap_Data_ival);
ZEND_NAMED_FUNCTION(_wrap_Data_uival);
ZEND_NAMED_FUNCTION(_wrap_Data_lval);
ZEND_NAMED_FUNCTION(_wrap_Data_ulval);
ZEND_NAMED_FUNCTION(_wrap_Data_fval);
ZEND_NAMED_FUNCTION(_wrap_Data_dval);
ZEND_NAMED_FUNCTION(_wrap_Data_sval);
ZEND_NAMED_FUNCTION(_wrap_Data_tval);
ZEND_NAMED_FUNCTION(_wrap_Data_setNull);
ZEND_NAMED_FUNCTION(_wrap_Data_setival);
ZEND_NAMED_FUNCTION(_wrap_Data_setuival);
ZEND_NAMED_FUNCTION(_wrap_Data_setlval);
ZEND_NAMED_FUNCTION(_wrap_Data_setulval);
ZEND_NAMED_FUNCTION(_wrap_Data_setdval);
ZEND_NAMED_FUNCTION(_wrap_Data_setsval);
ZEND_NAMED_FUNCTION(_wrap_Data_setblob);
ZEND_NAMED_FUNCTION(_wrap_Data_settimeval);
ZEND_NAMED_FUNCTION(_wrap_Data_print);
ZEND_NAMED_FUNCTION(_wrap_Data_setTag);
ZEND_NAMED_FUNCTION(_wrap_Data_getTag);
ZEND_NAMED_FUNCTION(_wrap_new_Record);
ZEND_NAMED_FUNCTION(_wrap_del_Record);
ZEND_NAMED_FUNCTION(_wrap_Record_clear);
ZEND_NAMED_FUNCTION(_wrap_Record_count);
ZEND_NAMED_FUNCTION(_wrap_Record_addField);
ZEND_NAMED_FUNCTION(_wrap_Record_pop);
ZEND_NAMED_FUNCTION(_wrap_Record_field);
ZEND_NAMED_FUNCTION(_wrap_Record_posWhoseNameIs);
ZEND_NAMED_FUNCTION(_wrap_Record_setFieldMap);
ZEND_NAMED_FUNCTION(_wrap_RecordSet_setFirst);
ZEND_NAMED_FUNCTION(_wrap_RecordSet_setLast);
ZEND_NAMED_FUNCTION(_wrap_RecordSet_setNext);
ZEND_NAMED_FUNCTION(_wrap_RecordSet_setPrev);
ZEND_NAMED_FUNCTION(_wrap_RecordSet_setWhereS);
ZEND_NAMED_FUNCTION(_wrap_RecordSet_setWhereI);
ZEND_NAMED_FUNCTION(_wrap_RecordSet_setPos);
ZEND_NAMED_FUNCTION(_wrap_RecordSet_dump);
ZEND_NAMED_FUNCTION(_wrap_RecordSet_know_nRows);
ZEND_NAMED_FUNCTION(_wrap_RecordSet_eof);
ZEND_NAMED_FUNCTION(_wrap_RecordSet_alwaysSameStructure);
ZEND_NAMED_FUNCTION(_wrap_RecordSet_nRows);
ZEND_NAMED_FUNCTION(_wrap_RecordSet_nFields);
ZEND_NAMED_FUNCTION(_wrap_RecordSet_pos);
ZEND_NAMED_FUNCTION(_wrap_RecordSet_rec);
ZEND_NAMED_FUNCTION(_wrap_RecordSet_metarec);
ZEND_NAMED_FUNCTION(_wrap_new_DBConn);
ZEND_NAMED_FUNCTION(_wrap_del_DBConn);
ZEND_NAMED_FUNCTION(_wrap_DBConn_connect);
ZEND_NAMED_FUNCTION(_wrap_DBConn_close);
ZEND_NAMED_FUNCTION(_wrap_DBConn_isOpen);
ZEND_NAMED_FUNCTION(_wrap_DBConn_newDBConn);
ZEND_NAMED_FUNCTION(_wrap_new_Query);
ZEND_NAMED_FUNCTION(_wrap_del_Query);
ZEND_NAMED_FUNCTION(_wrap_Query_query);
ZEND_NAMED_FUNCTION(_wrap_Query_prepare);
ZEND_NAMED_FUNCTION(_wrap_Query_prepare_with_parameters);
ZEND_NAMED_FUNCTION(_wrap_Query_nAffectedRows);
ZEND_NAMED_FUNCTION(_wrap_Query_param);
ZEND_NAMED_FUNCTION(_wrap_Query_lookup);
ZEND_NAMED_FUNCTION(_wrap_Query_gotRecordSet);
ZEND_NAMED_FUNCTION(_wrap_Query_execute);
ZEND_NAMED_FUNCTION(_wrap_Query_close);
ZEND_NAMED_FUNCTION(_wrap_new_Table);
ZEND_NAMED_FUNCTION(_wrap_del_Table);
ZEND_NAMED_FUNCTION(_wrap_Table_loadTable);
ZEND_NAMED_FUNCTION(_wrap_Table_newRec);
ZEND_NAMED_FUNCTION(_wrap_Table_insert);
ZEND_NAMED_FUNCTION(_wrap_Table_update);
ZEND_NAMED_FUNCTION(_wrap_new_Client);
ZEND_NAMED_FUNCTION(_wrap_del_Client);
ZEND_NAMED_FUNCTION(_wrap_Client_login);
ZEND_NAMED_FUNCTION(_wrap_Client_exec);
ZEND_NAMED_FUNCTION(_wrap_Client_code);
ZEND_NAMED_FUNCTION(_wrap_Client_msg);
ZEND_NAMED_FUNCTION(_wrap_Client_out);
ZEND_NAMED_FUNCTION(_wrap_Client_recv);
ZEND_NAMED_FUNCTION(_wrap_Client_aux);
ZEND_NAMED_FUNCTION(_wrap_new_Conf);
ZEND_NAMED_FUNCTION(_wrap_del_Conf);
ZEND_NAMED_FUNCTION(_wrap_Conf_sval);
ZEND_NAMED_FUNCTION(_wrap_Conf_ival);
#endif /* PHP_PHP2MCS_H */
